version: '3.7'

services:
  cassandra_seed:
    image: cassandra:3
    restart: always
    ports:
      - 9160:9160
      - 9042:9042
    networks:
      default:
        ipv4_address: 172.28.0.100
    environment:
      CASSANDRA_SEEDS: 172.28.0.100
  cassandra:
    image: cassandra:3
    restart: always
    ports:
      - 9160
      - 9042
    environment:
      CASSANDRA_SEEDS: 172.28.0.100
    depends_on:
      - "cassandra_seed"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet:  172.28.0.0/16

